add retries to workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -21,7 +21,18 @@ jobs:
       - run: npm run build
       - name: Deploy to Observable Cloud
         # This parameter to `--message` will use the latest commit message
-        run: npm run deploy -- --message "$(git log -1 --pretty=%s)"
+        run: max_attempts=3
+          count=0
+          until npm run deploy -- --message "$(git log -1 --pretty=%s)"
+          do
+            count=$((count+1))
+            if [ "$count" -eq "$max_attempts" ]; then
+              echo "Deployment failed after $count attempts"
+              exit 1
+            fi
+            echo "Deployment failed, retrying in 10 seconds..."
+            sleep 10
+          done
         env:
           # Authentication information. See below for how to set this up.
           OBSERVABLE_TOKEN: ${{ secrets.OBSERVABLE_TOKEN }}
